project:
  type: book

book:
  title: "A Modernised Thesis Template"
  author: "Doughnut"
  date: "today"
  chapters:
    - index.qmd
    - preamble/Abstract.qmd
    - preamble/Declaration.qmd
    - preamble/Preface.qmd
    - preamble/Acknowledgements.qmd
    - preamble/Glossary.qmd
    - preamble/Abbreviations.qmd
    - preamble/Constants.qmd
    - preamble/Symbols.qmd
    - chapters/Chapter1.qmd
  appendices:
    - appendices/AppendixA.qmd

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    template: ../templates/unimelb.tex
  typst:
    template: ../templates/thesis.typ
    toc: true
    lof: true
    lot: true
