verbatimEnvironments:
  - {name: verbatim, parse: false}
  - {name: Verbatim, parse: false}
  - {name: comment, parse: false}

# Default indentation
defaultIndent: "  "

# Environments
environments:
  # Default settings for all environments
  default:
    indent: "  "
    hangingIndent: "    "

# Special characters
specialBeginEnd:
  verbatim: 0
  Verbatim: 0
  comment: 0
