project:
  type: book
  output-dir: _book

book:
  title: "Thesis Title"
  author: "Your Name"
  date: "today"
  chapters:
    - index.qmd
    - preamble/Abstract.qmd
    - preamble/Acknowledgements.qmd
    - chapters/Chapter1.qmd
    - appendices/AppendixA.qmd
  appendices:
    - appendices/AppendixA.qmd

format:
  typst:
    template: templates/thesis.typ
    toc: true
