project:
  type: book
  output-dir: _book

book:
  title: "A Quarto PhD Thesis"
  author: "James D. Harding"
  date: "today"
  chapters:
    - index.qmd
    - preamble/Declaration.qmd
    - preamble/Abstract.qmd
    - preamble/Acknowledgements.qmd
    - chapters/Chapter1.qmd

  appendices:
    - appendices/AppendixA.qmd

format:
  typst:
    template: templates/thesis.typ
    toc: true

college: School for Infrastructure and Environment
degree: Doctor of Philosophy
year: 2023
supervisors: |
  Prof. A. Supervisor
  Dr. B. Co-supervisor
wordcount: |
  tbc
keywords: [template, demo]
bibliography: bibliography.bib
